### ISSUE TITLE
Get_page_list is broken

### ISSUE THREAD

**Issue by aulasau** [IvanProgramming/Telegraph_api#4]
Hello, man, again! :)
According to the [API doc](https://telegra.ph/api#getPageList), `get_page_list` returns PageList object.
https://github.com/IvanProgramming/Telegraph_api/blob/30a302d2a0bc9701a9b1c2c9799e7b3975465cfe/telegraph_api/api.py#L165-L166 
As I see here, `List[Page]` is used as the return type of `get_page_list`. 

For now, I'm getting the following exception, when trying to call `get_page_list`:
```Traceback (most recent call last):
  File "/Users/IvanProgramming/anaconda3/envs/nudes/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-f596fc14c206>", line 1, in <cell line: 1>
    created_pages = loop.run_until_complete(tr.tlgh.get_page_list())
  File "/Users/IvanProgramming/anaconda3/envs/nudes/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/IvanProgramming/anaconda3/envs/nudes/lib/python3.10/site-packages/telegraph_api/api.py", line 166, in get_page_list
    pages: List[Page] = await self.make_request(APIEndpoints.GET_PAGE_LIST, params=normalize_locals(locals()),
  File "/Users/IvanProgramming/anaconda3/envs/nudes/lib/python3.10/site-packages/telegraph_api/api.py", line 262, in make_request
    return parse_obj_as(model, data)
  File "/Users/IvanProgramming/anaconda3/envs/nudes/lib/python3.10/site-packages/pydantic/tools.py", line 35, in parse_obj_as
    return model_type(__root__=obj).__root__
  File "/Users/IvanProgramming/anaconda3/envs/nudes/lib/python3.10/site-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[List]
__root__
  value is not a valid list (type=type_error.list)
```

It looks like `get_page_list` is broken. It would be better if you added a `PageList` class with compatibility with the Telegraph documentation. Changing `List[Page]` to `PageList` is a *breaking change*, but it will fix this method. Because for now, it's: 

1. Return wrong type, `List[Page]` doesn't have `total count` property as mentioned in docs;
2. Raise an exception even when `GET` returns success.

**Comment by IvanProgramming** [comment]
Thanks for you attention and sorry for such long delay! I fixed this issue in new release
